# Generated by Django 5.2.4 on 2025-08-17 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'Leave'), ('outing', 'Outing')], max_length=10)),
                ('departure_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('address', models.TextField()),
                ('parent_type', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], default='Father', max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved by Warden'), ('rejected', 'Rejected'), ('issued', 'Pass Issued'), ('completed', 'Completed'), ('late', 'Late Entry')], default='pending', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actual_exit_time', models.DateTimeField(blank=True, null=True)),
                ('actual_entry_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_passes', to=settings.AUTH_USER_MODEL)),
                ('scaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scaned_passes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
