# Generated by Django 5.2.4 on 2025-08-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['-departure_datetime']},
        ),
    ]
