# Generated by Django 5.2.4 on 2025-08-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gatepass', '0002_alter_gatepass_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='actual_entry_time',
            new_name='entry_time',
        ),
        migrations.RenameField(
            model_name='gatepass',
            old_name='actual_exit_time',
            new_name='exit_time',
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to='accounts.wardens'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_passes', to='accounts.caretakers'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='scaned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scaned_passes', to='accounts.security'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='accounts.students'),
        ),
    ]
