# Generated by Django 5.2.4 on 2025-08-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_rename_actual_entry_time_gatepass_entry_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='scaned_by',
            new_name='scanned_by',
        ),
    ]
