# Generated by Django 5.2.4 on 2025-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_rename_scaned_by_gatepass_scanned_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved by Warden'), ('rejected', 'Rejected'), ('issued', 'Pass Issued'), ('off_campus', 'Off Campus'), ('completed', 'Completed'), ('late', 'Late Entry')], default='pending', max_length=20),
        ),
    ]
